hilton_db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: admin
    MYSQL_DATABASE: hilton_app_database
  ports:
    - "3306:3306"