# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  app.baseurl: https://content-api.hiltonapps.com/v1/places/top-places
  app.authtoken: jobs383-UgWfVvxQXNhDQLw4v

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

#   Processing Classes
    App\Processor\FourSquareProcessor:
        autowire: false
        autoconfigure: false
        public: true
        parent: App\Processor\Processor
        tags: [app.processor.service]

    App\Processor\ViatorProcessor:
        autowire: false
        autoconfigure: false
        public: true
        parent: App\Processor\Processor
        tags: [app.processor.service]

    App\Processor\TimeoutProcessor:
        autowire: false
        autoconfigure: false
        public: true
        parent: App\Processor\Processor
        tags: [app.processor.service]

    App\Processor\Processor:
        autowire: false
        autoconfigure: false
        public: true
        abstract:  true
        arguments: ['%app.baseurl%', '@App\ApiClient\ApiClient', '%app.authtoken%', '@doctrine.orm.entity_manager', '@logger']

    App\Processor\ProcessorRunner:
        autowire: false
        autoconfigure: false
        public: true
        arguments: [!tagged app.processor.service]

#   Output Classes
    App\Repository\FourSquareLocationRepository:
        autowire: true
        autoconfigure: false
        public: true
        tags: [app.output.repository.service]

    App\Repository\TimeoutLocationRepository:
        autowire: true
        autoconfigure: false
        public: true
        tags: [app.output.repository.service]

    App\Repository\ViatorLocationRepository:
        autowire: true
        autoconfigure: false
        public: true
        tags: [app.output.repository.service]

    App\Controller\OutputController:
        autowire: false
        autoconfigure: false
        public: true
        arguments: [!tagged app.output.repository.service]